name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
      - run: |
        echo "A initial message"
        echo "Hello World!"
        git --version
        env
